/**
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 */
package leetcode;

import java.util.HashMap;

public class LeetCode389FindtheDifference {

    public char findTheDifference(String s, String t) {

        if (null == s || null == t) {
            return ' ';
        }

        HashMap<Character, Integer> map = new HashMap<>();

        for (int i = 0; i < s.length(); i++) {
            if (!map.containsKey(s.charAt(i))) {
                map.put(s.charAt(i), 1);
            } else {
                map.put(s.charAt(i), map.get(s.charAt(i)) + 1);
            }
        }

        for (int i = 0; i < t.length(); i++) {
            if (!map.containsKey(t.charAt(i)) || 0 == map.get(t.charAt(i))) {
                return t.charAt(i);
            }

            map.put(t.charAt(i), map.get(t.charAt(i)) - 1);
        }

        return ' ';

    }
}
